// app/about/page.js
export default function AboutPage() {
	return (
	  <div style={{ padding: '20px', fontFamily: 'Arial, sans-serif' }}>
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
		nfjdsg<br />
		sjfhsbvs<br />
		vdfsvs<br />
		gsfd<br />
	  </div>
	);
  }
  